export default function () {
    const magicLink = "http://localhost:3000/api/auth/magiclink/callback?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZWRpcmVjdCI6Ii9jaGVjay1tYWlsYm94P2U9YWxpbmF1cm96ZUBob3RtYWlsLmNvbSIsImRlc3RpbmF0aW9uIjoiYWxpbmF1cm96ZUBob3RtYWlsLmNvbSIsInJlbWVtYmVyTWUiOmZhbHNlLCJjb2RlIjoiNTYxOTUiLCJpYXQiOjE2Njg0NTE0MjYsImV4cCI6MTY2ODQ1NTAyNn0.EwS6jRAi0vVLCRQsHsQ8w4lsaz62BTtbhepr6zuQAiw";
    cy.visit(magicLink);
}